"""add typo check jobs table

Revision ID: 7228e64ce25a
Revises: 5f2cd4f23956
Create Date: 2026-02-06 15:15:20.580940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7228e64ce25a'
down_revision = '5f2cd4f23956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('typo_check_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('original_text_hash', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress_current', sa.Integer(), nullable=False),
    sa.Column('progress_total', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['result_id'], ['typo_check_results.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('typo_check_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_typo_check_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_typo_check_jobs_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('typo_check_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_typo_check_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_typo_check_jobs_status'))

    op.drop_table('typo_check_jobs')
    # ### end Alembic commands ###
